#!/usr/bin/python
#
# Cloud.com Bridge DB setup script.
#

from getpass import getpass 
from subprocess import call

setup_db_dir = '/usr/share/cloud/setup/bridge/db'
setup_db_script = 'deploy-db-bridge.sh'

print 'Welcome to CloudBridge Database setup.'
passwd = getpass('Please enter the MySQL password for root@localhost: ')

call(['/bin/bash', setup_db_script, 'cloud', 'root', passwd], cwd=setup_db_dir)
