github:
  description: "Apache CloudStack is an opensource Infrastructure as a Service (IaaS) cloud computing platform"
  homepage: https://cloudstack.apache.org/
  labels:
    - iaas
    - cloud
    - cloudstack
    - infrastructure
    - java
    - python
    - kvm
    - libvirt
    - vsphere
    - vmware
    - xenserver
    - xcp-ng
    - orchestration
    - virtualization
    - virtual-machine
    - kubernetes

  features:
    wiki: true
    issues: true
    discussions: true
    projects: true

  enabled_merge_buttons:
    merge: false
    squash: true
    rebase: false

  collaborators:
    - ingox
    - gp-santos
    - erikbocks
    - Imvedansh
    - Damans227
    - jmsperu
    - GaOrtiga
    - bhouse-nexthop

  protected_branches:

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true

  copilot_code_review:
    enabled: true
    review_drafts: true
    review_on_push: true

notifications:
  commits: commits@cloudstack.apache.org
  issues: commits@cloudstack.apache.org
  pullrequests: commits@cloudstack.apache.org
  discussions: users@cloudstack.apache.org
