package org.apache.cloudstack.api;

public enum ApiCommandJobType {
    None,
    VirtualMachine,
    DomainRouter,
    Volume,
    ConsoleProxy,
    Snapshot,
    Template,
    Iso,
    SystemVm,
    Host,
    StoragePool,
    IpAddress,
    PortableIpAddress,
    SecurityGroup,
    PhysicalNetwork,
    TrafficType,
    PhysicalNetworkServiceProvider,
    FirewallRule,
    Account,
    User,
    PrivateGateway,
    StaticRoute,
    Counter,
    Condition,
    AutoScalePolicy,
    AutoScaleVmProfile,
    AutoScaleVmGroup,
    GlobalLoadBalancerRule,
    LoadBalancerRule,
    AffinityGroup,
    InternalLbVm,
    DedicatedGuestVlanRange
}