#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
set -x
old_checksum_path="$HOME/.m2/repository/.cache/download-maven-plugin/"
new_checksum_path="./dist/systemvm-templates/"
file_name="md5sum.txt"

count=$(ls -d ${old_checksum_path}${file_name}* | wc -l)
if [ "$count" -gt 1 ]; then
  rm -rf $old_checksum_path*
else
  echo $PWD
  old_checksum=$(md5sum ${old_checksum_path}${file_name}* | awk '{print $1}')
  new_checksum=$(md5sum ${new_checksum_path}${file_name} | awk '{print $1}')
  if [ "$old_checksum" != "$new_checksum" ]; then
    rm -rf $old_checksum_path*
  else
    echo "equal"
  fi
fi
