#!/bin/sh

# the following is chkconfig init header
#
# cs-sgagent:  cloudStack baremetal sercurity group agent
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by CloudStack management server \
#               to perform baremetal security group related operations\
#
# processname: cs-sgagent
# pidfile: /var/run/cssgagent.pid
#

check_status() {
	pidfile='/var/run/cssgagent.pid'
	if [ ! -f $pidfile ]; then
		echo "cloudstack baremetal security group agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "cloudstack baremetal security group agent is running, pid is $pid"
			exit 0
		else
			echo "cloudstack baremetal security group agent is stopped, but pidfile at $pidfile is not cleaned. It may be caused by the agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
    python -c "from security_group_agent import cs_sg_agent; cs_sg_agent.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ cloudstack baremetal security group agent .... SUCCESS"
    exit 0
else
    echo "$@ cloudstack baremetal security group agent .... FAILED"
    exit 1
fi
