# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# MD001/heading-increment Heading levels should only increment by one level at a time
MD001: false

# MD003/heading-style Heading style
MD003: false

# MD004/ul-style Unordered list style
MD004: false

# MD007/ul-indent Unordered list indentation
MD007: false

# MD009/no-trailing-spaces Trailing spaces
MD009: false

# MD010/no-hard-tabs Hard tabs
MD010: false

# MD012/no-multiple-blanks Multiple consecutive blank lines
MD012: false

# MD013/line-length Line length
MD013: false

# MD014/commands-show-output Dollar signs used before commands without showing output
MD014: false

# MD018/no-missing-space-atx No space after hash on atx style heading
MD018: false

# MD019/no-multiple-space-atx Multiple spaces after hash on atx style heading
MD019: false

# MD022/blanks-around-headings Headings should be surrounded by blank lines
MD022: false

# MD023/heading-start-left Headings must start at the beginning of the line
MD023: false

# MD024/no-duplicate-heading Multiple headings with the same content
MD024: false

# MD025/single-title/single-h1 Multiple top-level headings in the same document
MD025: false

# MD026/no-trailing-punctuation Trailing punctuation in heading
MD026: false

# MD028/no-blanks-blockquote Blank line inside blockquote
MD028: false

# MD029/ol-prefix Ordered list item prefix
MD029: false

# MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines
MD031: false

# MD032/blanks-around-lists Lists should be surrounded by blank lines
MD032: false

# MD033/no-inline-html Inline HTML
MD033: false

# MD034/no-bare-urls Bare URL used
MD034: false

# MD036/no-emphasis-as-heading Emphasis used instead of a heading
MD036: false

# MD037/no-space-in-emphasis Spaces inside emphasis markers
MD037: false

# MD040/fenced-code-language Fenced code blocks should have a language specified
MD040: false

# MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading
MD041: false

# MD046/code-block-style Code block style
MD046: false

# MD052/reference-links-images Reference links and images should use a label that is defined
MD052: false
