# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

/usr/lib/cloud/agent/scripts/installer/*
/usr/lib/cloud/agent/scripts/network/*
/usr/lib/cloud/agent/scripts/storage/*
/usr/lib/cloud/agent/scripts/util/*
/usr/lib/cloud/agent/scripts/vm/network/*
/usr/lib/cloud/agent/scripts/vm/systemvm/*
/usr/lib/cloud/agent/scripts/vm/pingtest.sh
/usr/lib/cloud/agent/scripts/vm/hypervisor/kvm/*
/usr/lib/cloud/agent/scripts/vm/hypervisor/versions.sh
/usr/lib/cloud/agent/scripts/vm/hypervisor/xenserver/*
