#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# clear processed files in /var/cache/cloud/processed

THRESHOLD=80
DIRECTORY=/var/cache/cloud/processed
DAYS=180
MIN_DAYS=5

if [ ! -d $DIRECTORY ];then
    echo "$DIRECTORY not found"
    exit 0
fi

percent=$(df --output=pcent $DIRECTORY | tr -dc '0-9')

while [[ $percent -gt $THRESHOLD ]] && [[ $DAYS -gt $MIN_DAYS ]];do
    echo "Removing files in $DIRECTORY older than $DAYS days"
    find $DIRECTORY -type f -a -mtime +$DAYS -delete
    DAYS=$((DAYS-1))
    percent=$(df --output=pcent $DIRECTORY | tr -dc '0-9')
done
