language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4

install:
    - pip install 'setuptools>=18.5,<=39.0.0'
    - pip install -r test-requirements.txt

script: python setup.py nosetests --verbosity=3
