#!/bin/bash -e
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

(/opt/bin/kubectl get pods -A | grep cloud-controller-manager) && exit 0

if [ -e /opt/provider/provider.yaml ]; then
    /opt/bin/kubectl apply -f /opt/provider/provider.yaml
    exit 0
else
    mkdir -p /opt/provider
    PROVIDER_URL="https://raw.githubusercontent.com/apache/cloudstack-kubernetes-provider/main/deployment.yaml"
    provider_conf_file="/opt/provider/provider.yaml"
    curl -sSL ${PROVIDER_URL} -o ${provider_conf_file}
    if [ $? -ne 0 ]; then
        echo "Unable to connect to the internet to download the provider deployment and image"
        exit 1
    else
        /opt/bin/kubectl apply -f /opt/provider/provider.yaml
        exit 0
    fi
fi
