#! /bin/bash
function usage() {
    cat << USAGE
Usage: ./deploy-cloudstack-secret [OPTIONS]...
Enables autoscaling for the kubernetes cluster.
Arguments:
  -u, --url string         ID of the cluster
  -k, --key string         Enables autoscaling
  -s, --secret string      Disables autoscaling
Other arguments:
  -h, --help              Display this help message and exit
Examples:
  ./deploy-cloudstack-secret -u http://localhost:8080 -k abcd -s efgh
USAGE
    exit 0
}
API_URL=""
API_KEY=""
SECRET_KEY=""
while [ -n "$1" ]; do
    case "$1" in
        -h | --help)
            usage
            ;;
        -u | --url)
            API_URL=$2
            shift 2
            ;;
        -k | --key)
            API_KEY=$2
            shift 2
            ;;
        -s | --secret)
            SECRET_KEY=$2
            shift 2
            ;;
        -*|*)
            echo "ERROR: no such option $1. -h or --help for help"
            exit 1
            ;;
    esac
done
cat > /tmp/cloud-config <<EOF
[Global]
api-url = $API_URL
api-key = $API_KEY
secret-key = $SECRET_KEY
EOF
# Create secret if not exists
kubectl -n kube-system get secret cloudstack-secret || kubectl -n kube-system create secret generic cloudstack-secret --from-file=/tmp/cloud-config
rm /tmp/cloud-config
