#!/bin/bash

export PATH=$PATH:/opt/bin
node_name=$1
node_type=$2
operation=$3

if [ $operation == "remove" ]; then
  if [ $node_type == "control" ]; then
    # get the specific node
    kubectl get nodes $node_name >/dev/null 2>&1
    if [[ $(echo $?) -eq 1 ]]; then
       echo "No node with name $node_name present in the cluster, exiting..."
       exit 0
    else
       # Drain the node
       kubectl drain $node_name --delete-local-data --force --ignore-daemonsets
    fi
  else
    kubeadm reset -f
  fi
else
  sudo mkdir -p /home/cloud/.kube
  sudo cp /root/.kube/config /home/cloud/.kube/
  sudo chown -R cloud:cloud /home/cloud/.kube
  kubectl delete node $node_name
fi