#!/bin/bash -e
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

REGISTRY_URL=`cat /opt/cks/registry_url`
REGISTRY_URL_ENDPOINT=`cat /opt/cks/registry_url_endpoint`
REGISTRY_USERNAME=`cat /opt/cks/registry_username`
REGISTRY_PASSWORD=`cat /opt/cks/registry_password`
REGISTRY_TOKEN=`cat /opt/cks/registry_token`

export registryConfig="\\        [plugins.\"io.containerd.grpc.v1.cri\".registry.mirrors.\"$REGISTRY_URL_ENDPOINT\"]\n \\         endpoint = [\"$REGISTRY_URL\"]"
export registryCredentials="\\      [plugins.\"io.containerd.grpc.v1.cri\".registry.configs.\"$REGISTRY_URL_ENDPOINT\".auth]\n\tusername = \"$REGISTRY_USERNAME\" \n\tpassword = \"$REGISTRY_PASSWORD\" \n\tidentitytoken = \"$REGISTRY_TOKEN\""

echo "creating config file for containerd"
containerd config default > /etc/containerd/config.toml
sed  -i '/\[plugins."io.containerd.grpc.v1.cri".registry\]/a '"${registryCredentials}"'' /etc/containerd/config.toml
sed  -i '/\[plugins."io.containerd.grpc.v1.cri".registry.mirrors\]/a '"${registryConfig}"'' /etc/containerd/config.toml

echo "Restarting containerd service"
systemctl restart containerd
