#!/bin/bash -e

ISO_MOUNT_DIR=/mnt/k8sdisk
BINARIES_DIR=${ISO_MOUNT_DIR}/
MOUNT_ATTEMPT_SLEEP=15
MOUNT_ATTEMPTS=1
while true; do
  set +e
  output=`blkid -o device -t TYPE=iso9660`
  set -e
  if [ "$output" != "" ]; then
    while read -r line; do
      if [ ! -d "${ISO_MOUNT_DIR}" ]; then
        mkdir "${ISO_MOUNT_DIR}"
      fi
      retval=0
      set +e
      mount -o ro "${line}" "${ISO_MOUNT_DIR}"
      retval=$?
      set -e
      if [ $retval -eq 0 ]; then
        if [ -d "$BINARIES_DIR" ]; then
          break
        else
          umount "${line}" && rmdir "${ISO_MOUNT_DIR}"
        fi
      fi
    done <<< "$output"
  fi
  if [ -d "$BINARIES_DIR" ]; then
    break
  fi
  echo "Waiting for Binaries directory $BINARIES_DIR to be available, sleeping for $MOUNT_ATTEMPT_SLEEP seconds, attempt: $MOUNT_ATTEMPTS"
  sleep $MOUNT_ATTEMPT_SLEEP
  MOUNT_ATTEMPTS=$[$MOUNT_ATTEMPTS + 1]
done
echo "Done mounting iso"

set +e
cp $ISO_MOUNT_DIR/scripts/* /opt/bin/
echo "Done copying scripts"
