#!/bin/bash -e

REGISTRY_URL=`cat /opt/cks/registry_url`
REGISTRY_URL_ENDPOINT=`cat /opt/cks/registry_url_endpoint`
REGISTRY_USERNAME=`cat /opt/cks/registry_username`
REGISTRY_PASSWORD=`cat /opt/cks/registry_password`
REGISTRY_TOKEN=`cat /opt/cks/registry_token`

export registryConfig="\\        [plugins.\"io.containerd.grpc.v1.cri\".registry.mirrors.\"$REGISTRY_URL_ENDPOINT\"]\n \\         endpoint = [\"$REGISTRY_URL\"]"
export registryCredentials="\\      [plugins.\"io.containerd.grpc.v1.cri\".registry.configs.\"$REGISTRY_URL_ENDPOINT\".auth]\n\tusername = \"$REGISTRY_USERNAME\" \n\tpassword = \"$REGISTRY_PASSWORD\" \n\tidentitytoken = \"$REGISTRY_TOKEN\""

echo "creating config file for containerd"
containerd config default > /etc/containerd/config.toml
sed  -i '/\[plugins."io.containerd.grpc.v1.cri".registry\]/a '"${registryCredentials}"'' /etc/containerd/config.toml
sed  -i '/\[plugins."io.containerd.grpc.v1.cri".registry.mirrors\]/a '"${registryConfig}"'' /etc/containerd/config.toml

echo "Restarting containerd service"
systemctl restart containerd
