package org.apache.cloudstack.acl;

public enum AclEntityType {
    // currently supported entity, to be added one by one after we support acl on the entity
    VirtualMachine,
    Volume,
    ResourceTag,
    Account,
    AffinityGroup,
    AutoScalePolicy,
    AutoScaleVmGroup,
    AutoScaleVmProfile,
    Condition,
    Vpc,
    VpcGateway,
    VpnUser,
    VMSnapshot,
    VirtualMachineTemplate,
    UserIpv6Address,
    StaticRoute,
    SSHKeyPair,
    Snapshot,
    Site2SiteVpnGateway,
    Site2SiteVpnConnection,
    Site2SiteCustomerGateway,
    SecurityGroup,
    RemoteAccessVpn,
    PublicIpAddress,
    ProjectInvitation,
    NicSecondaryIp,
    NicIpAlias,
    Network,
    IpAddress,
    InstanceGroup,
    GlobalLoadBalancerRule,
    FirewallRule,
    Event,
    AsyncJob,
    AclPolicy,
    AclGroup,
    MonitorService,
    SSLCert
}
