#!/bin/sh
# the following is chkconfig init header
#
# cs-sgagent:  cloudStack baremetal security group agent
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by CloudStack management server \
#               to perform baremetal security group related operations\
#
# processname: cs-sgagent
# pidfile: /var/run/cssgagent.pid
#

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

check_status() {
    pidfile='/var/run/cssgagent.pid'
    if [ ! -f $pidfile ]; then
        echo "cloudstack baremetal security group agent is stopped"
        exit 1
    else
        pid=`cat $pidfile`
        ps -p $pid > /dev/null
        if [ $? -eq 0 ]; then
            echo "cloudstack baremetal security group agent is running, pid is $pid"
            exit 0
        else
            echo "cloudstack baremetal security group agent is stopped, but pidfile at $pidfile is not cleaned. It may be caused by the agent crashed at last time, manually cleaning it would be ok"
            exit 1
        fi
    fi
}

if [ $# -eq 0 ]; then
    echo "usage: $0
[start|stop|restart|status]"
    exit 1
fi

if [ "$@" = "status" ]; then
    check_status
else
    python -c "from security_group_agent import cs_sg_agent; cs_sg_agent.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ cloudstack baremetal security group agent .... SUCCESS"
    exit 0
else
    echo "$@ cloudstack baremetal security group agent .... FAILED"
    exit 1
fi
