// VMOpsInstanceManager.idl : IDL source for VMOps Instance Manager
//

// This file will be processed by the MIDL tool to
// produce the type library (VMOpsInstanceManager.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(5F9080A7-CF0E-4EC5-B461-9B817882DF23),
	version(1.0),
	helpstring("VMOpsInstanceManager 1.0 Type Library")
]
library VMOpsInstanceManagerLib
{
	importlib("stdole2.tlb");
};
